---

- name: restart_node_exporter
  systemd:
    name: prometheus-node-exporter
    state: restarted

- name: restart_tor_exporter
  systemd:
    name: prometheus-tor-exporter
    state: restarted

- name: reload_systemd
  systemd:
    daemon_reload: yes
