---

- hosts: localhost
  tasks:
    - name: Create local tmp dir
      file:
        path: /tmp/tor_keys
        state: directory
        mode: 0700
      delegate_to: localhost
      become: false
      run_once: true

    - name: Update backup repo
      command: git submodule update --remote
      delegate_to: localhost
      become: false
      run_once: true


- hosts: all-servers
  tasks:
    - name: Read ed25519_master_id_secret_key
      fetch:
        src: /var/lib/tor/keys/ed25519_master_id_secret_key
        dest: /tmp/tor_keys/{{ inventory_hostname }}-ed25519_master_id_secret_key
        flat: yes

    - name: Read secret_id_key
      fetch:
        src: /var/lib/tor/keys/secret_id_key
        dest: /tmp/tor_keys/{{ inventory_hostname }}-secret_id_key
        flat: yes

    - name: Insert ed25519_master_id_secret_key into password store
      shell: |
        age -R ~/.ssh/id_ed25519.pub /tmp/tor_keys/{{ inventory_hostname }}-ed25519_master_id_secret_key > ansible-tor-backup/tor/{{ inventory_hostname }}-ed25519_master_id_secret_key.age
      delegate_to: localhost
      become: false

    - name: Insert secret_id_key into password store
      shell: |
        age -R ~/.ssh/id_ed25519.pub /tmp/tor_keys/{{ inventory_hostname }}-secret_id_key > ansible-tor-backup/tor/{{ inventory_hostname }}-secret_id_key.age
      delegate_to: localhost
      become: false

- hosts: localhost
  tasks:
    - name: Stage backup repo
      command: 
        cmd: git add .
        chdir: ansible-tor-backup
      delegate_to: localhost
      become: false
      run_once: true

    - name: Commit backup repo
      command: 
        cmd: git commit -m "Automated backup {{ ansible_date_time.iso8601 }}"
        chdir: ansible-tor-backup
      delegate_to: localhost
      become: false
      run_once: true

    - name: Push backup repo
      command: 
        cmd: git push origin HEAD:main
        chdir: ansible-tor-backup
      delegate_to: localhost
      become: false
      run_once: true

    - name: Refresh submodule
      command: git submodule update --remote
      delegate_to: localhost
      become: false
      run_once: true

    - name: Delete local keys directory
      file:
        path: /tmp/tor_keys
        state: absent
      delegate_to: localhost
      become: false
      run_once: true
