---

- name: Install unbound
  apt:
    name: unbound
    state: latest

- name: Set resolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 0444

- name: Copy unbound-control-setup
  copy:
    src: unbound-control-setup
    dest: /etc/unbound/unbound-control-setup
    mode: 0744

- name: Check if keys are already generated
  stat:
    path: /etc/unbound/unbound_ca_ec.key
  register: unbound_ca_file

- name: Generate keys if not exist
  command: /etc/unbound/unbound-control-setup
  when: not unbound_ca_file.stat.exists

- name: Enable control for exporter
  copy:
    src: control.conf
    dest: /etc/unbound/unbound.conf.d/control.conf
    mode: 0644
  notify: restart_unbound

- name: Enable stats for exporter
  copy:
    src: extended-stats.conf
    dest: /etc/unbound/unbound.conf.d/extended-stats.conf
    mode: 0644
  notify: restart_unbound

- name: Disable ipv6
  copy:
    src: disable-ipv6.conf
    dest: /etc/unbound/unbound.conf.d/disable-ipv6.conf
    mode: 0644
  notify: restart_unbound
  when: ipv6_disabled|default(true)

- name: Enable ipv6
  file:
    path: /etc/unbound/unbound.conf.d/disable-ipv6.conf
    state: absent
  notify: restart_unbound
  when: not (ipv6_disabled|default(true))

- name: Enable unbound
  systemd:
    name: unbound
    state: started
    enabled: yes

