---

- name: Install tor-exporter
  apt:
    deb: https://github.com/atx/prometheus-tor_exporter/releases/download/v0.4/prometheus-tor-exporter_0.4_all.deb
    state: present

- name: Set tor-exporter configuration
  template:
    src: prometheus-tor-exporter
    dest: /etc/default/prometheus-tor-exporter
    owner: root
    group: root
    mode: 0644
  notify: restart_tor_exporter

- name: Start tor-exporter
  systemd:
    name: prometheus-tor-exporter
    state: started
    enabled: yes
