---

- name: Install apt-transport-https and gpg
  apt:
    name: [apt-transport-https, gpg, gpg-agent]
    state: latest

- name: Add Tor repository key
  apt_key:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    state: present

- name: Add Tor repository
  apt_repository:
    repo: deb https://deb.torproject.org/torproject.org buster main
    state: present
    update_cache: yes

- name: Install Tor keyring
  apt:
    name: deb.torproject.org-keyring
    state: latest

- name: Install Tor and Nyx
  apt:
    name: [tor, nyx]
    state: latest
    update-cache: yes

- name: Create Nyx config dir
  file:
    path: /root/.nyx
    state: directory

- name: Write Nyx config
  template:
    src: nyxrc
    dest: /root/.nyx/config
    owner: root
    group: root
    mode: 0644
