---

- name: Install unattended upgrades packages
  apt:
    name: ['unattended-upgrades', 'apt-listchanges']
    state: latest

- name: Set unattended upgrades config
  template:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Activate unattended upgrades
  debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: "true"
    vtype: boolean
  notify: reconfigure_unattended_upgrades

